In [2]:
import numpy as np
import scipy as sp
from scipy.stats import unitary_group, ortho_group


In [2]:
dim = 5
dim_A = 3
dim_B = dim-dim_A

U = unitary_group.rvs(dim)
U_AA = U[:dim_A,:dim_A]
U_AB = U[:dim_A,dim_A:]
U_BA = U[dim_A:,:dim_A]
U_BB = U[dim_A:,dim_A:]

In [4]:
S_A, c_A, T_Ah = sp.linalg.svd(U_AA)
S_B, c_B, T_Bh = sp.linalg.svd(U_BB)

In [5]:
print(c_A)
print(c_B)

[1.         0.83913313 0.19568059]
[0.83913313 0.19568059]


In [6]:
m = S_A.conj().T @ U_AB @ T_Bh.conj().T
print(np.round(m,5))

[[ 0.     +0.j      -0.     -0.j     ]
 [-0.35576-0.41145j  0.     +0.j     ]
 [ 0.     +0.j       0.57367+0.79537j]]


In [7]:
Phi_A = 1/np.sqrt(2)*np.block(
    [[U_AA, U_AB],
    [np.identity(dim_A),np.zeros((dim_A,dim_B))]]
)
U, s, Vh = sp.linalg.svd(Phi_A)

In [8]:
print(s)

[1.         0.95894033 0.77320133 0.63416063 0.28360789]


In [11]:
print(np.sqrt((c_A**2+1)/2))

[1.         0.92307757 0.72051748]


In [4]:
dim = 5
dim_A = 3
dim_B = dim-dim_A

O = ortho_group.rvs(dim)
O_AA = O[:dim_A,:dim_A]
O_AB = O[:dim_A,dim_A:]
O_BA = O[dim_A:,:dim_A]
O_BB = O[dim_A:,dim_A:]

S_A, c_A, T_Ah = sp.linalg.svd(O_AA)
S_B, c_B, T_Bh = sp.linalg.svd(O_BB)

In [5]:
print(c_A)
print(c_B)

[1.         0.3163506  0.26458569]
[0.3163506  0.26458569]


In [9]:

index = np.array([True, False, True])

a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
a[:,index]


array([[1, 3],
       [4, 6],
       [7, 9]])

In [3]:
m = np.array(
    [[1,0],
    [0,0]])
sp.linalg.svd(m)


(array([[1., 0.],
        [0., 1.]]),
 array([1., 0.]),
 array([[1., 0.],
        [0., 1.]]))